alfax/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
urlpatterns = [
    path('dashboard/karfarmaonline/', include('karfarmaonline.urls')),
    path('', include('land.urls')),
    path('', include("authentication.urls")), 
    path('dashboard/', include('dashboard.urls')),
    path('blog/', include('blog.urls')),
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG :
    urlpatterns += [
        # ... the rest of your URLconf goes here ...
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path

from . import views


app_name = "bloga"

urlpatterns = [
    path('', views.blog_view, name='blog'),
    re_path(r'article/(?P<slug>[-\w]+)/', views.article_detail, name="detail"),
]

projects/urls.py
from django.urls import path, re_path
from . import views


app_name = "project"

urlpatterns = [
    re_path(r'detail/(?P<slug>[-\w]+)/', views.project_detail, name="detail"),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from extensions.utils import jalali_converter, jalali_converter_2

#### set up Manager 
class ProjectManager(models.Manager):
    def published(self):
        dic = {}
        projects = Projects_detail.objects.filter(status = 'p').order_by('-publish_date')
        for project in projects:
            list_category =[]
            cats = Projects_detail.objects.get(project_slug = project.slug).skillss_category.all()
            for cat in cats:
                list_category.append(cat)
            dic[project]= list_category

        return dic

    def categories(self,slug):   #### TODO Change this method on another Objects
        titles = []
        items = self.get(project_slug = slug).skillss_category.all()
        for item in items:
            titles.append(item.title)
        return titles 




#### -------------> Project Page DB start
class Skills_category(models.Model):
    title = models.CharField(max_length=200 ,verbose_name="عنوان")
    slug = models.SlugField(max_length=100 ,unique=True,allow_unicode=True,verbose_name="اسلاگ")
    status = models.BooleanField(default=True ,verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta :
        verbose_name = "دسته بندی پروژه"
        verbose_name_plural= "دسته بندی پروژه  بر اساس مهارت"
        ordering = ['position']

    def __str__(self):
        return self.title
    def __unicode__(self):
        return self.title


class Projects_detail(models.Model):

    STATUS_CHOICES = (
        ('d','پیش نویس'),
        ('p', 'منتشر شده'),
    )
    project_title = models.CharField(max_length=200 ,verbose_name="عنوان پروژه")
    project_customer = models.CharField(max_length=200, default=None ,verbose_name="سفارش دهنده یا مشتری پروژه")
    project_subject = models.CharField(max_length=200 ,verbose_name="موضوع پروژه یا توضیح کوتاه")
    project_slug = models.SlugField(max_length=100 ,unique=True,allow_unicode=True,verbose_name="اسلاگ پروژه")
    project_description = models.TextField(default=None,verbose_name="توضیحات")
    project_thumbnail = models.ImageField(upload_to="project_image",verbose_name="تصویر")
    project_address =  models.CharField(max_length=200 ,verbose_name="آدرس پروژه")
    skillss_category = models.ManyToManyField(Skills_category,verbose_name="دسته بندی پروژه بر اساس مهارت ")
    publish_date = models.DateTimeField(auto_now=True,verbose_name="تاریخ انتشار")
    start_date = models.DateTimeField(default=timezone.now,verbose_name="تاریخ شروع پروژه")
    end_date = models.DateTimeField(default=timezone.now,verbose_name="تاریخ  پایان پروژه")

    status = models.CharField(max_length=1, choices=STATUS_CHOICES,verbose_name="وضعیت")

    objects = ProjectManager()
    
    class Meta :
        verbose_name = "پروژه ها"
        verbose_name_plural= "پروژه ها"

    def __str__(self):
        return self.project_title
    def __unicode__(self):
        return self.project_title

    def jday(self):
        day, month, year = jalali_converter_2(self.end_date)
        return day

    def jmonth(self):
        day, month, year = jalali_converter_2(self.end_date)
        return month
        
    def jyear(self):
        day, month, year = jalali_converter_2(self.end_date)
        return year
#### -------------> Project Page DB End

projects/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django import template
from .models import *
from blog.models import *
from django.contrib.auth.models import User


def project_detail(request,slug):
    project = Projects_detail.objects.filter(project_slug =slug)
    last4project = Projects_detail.objects.filter(status='p')

    post_cat  = Projects_detail.objects.categories(slug = slug)

    context = {
        "project": project,
        "last4":last4project, 
        "project_category":post_cat,
        "categories":Category.objects.all(),
        "last3":Article.objects.filter(status= 'p').order_by('-publish')[:3]
     }
    return render(request, "projects/project_detail.html", context) 

templates/projects/base.html
<!DOCTYPE html>
<html dir="rtl">
	<head>

		<!-- Basic -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">	

        <title>ALFAX | پروژه ها{% block title%}{% endblock %}</title>

		<meta name="keywords" content="HTML5 Template">
		<meta name="description" content="Porto - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Favicon -->
		<link rel="shortcut icon" href="/static/porto/img/favicon.ico" type="image/x-icon">
		<link rel="apple-touch-icon" href="/static/porto/img/apple-touch-icon.png">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

        {% block css %}
        {% endblock %}

	</head>
	<body>

		<div class="body">
			<header id="header" class="header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyChangeLogo': true, 'stickyStartAt': 30, 'stickyHeaderContainerHeight': 70}">
				<div class="header-body border-top-0">
					<div class="header-container container-fluid px-lg-4">
						<div class="header-row">
							<div class="header-column header-column-border-right flex-grow-0">
								<div class="header-row pr-4">
									<div class="header-logo">
										<a href="index.html">
											<img alt="Porto" width="100" height="48" data-sticky-width="82" data-sticky-height="40" src="/static/porto/img/logo.png">
										</a>
									</div>
								</div>
							</div>
							<div class="header-column">
								<div class="header-row">
									<div class="header-nav header-nav-links justify-content-center">
										<div class="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1">
											<nav class="collapse">
												<ul class="nav nav-pills" id="mainNav">
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="/">
															خانه
														</a>
													</li>
													<li class="dropdown dropdown-mega">
														<a class="dropdown-item dropdown-toggle" href="/dashboard">
															سیستم مدیریت
														</a>
													</li>
													<li class="dropdown dropdown-mega">
														<a class="dropdown-item dropdown-toggle" href="#">
															آموزش ها
														</a>
													</li>
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="/">
															پروژه ها
														</a>
													</li>
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="/blog">
															بلاگ
														</a>
													</li>
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="/login">
															ورود/ثبت نام
														</a>
													</li>

													
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="#">
															تماس با ما
														</a>
													</li>
													<li class="dropdown">
														<a class="dropdown-item dropdown-toggle" href="#">
															فروشگاه
														</a>
														<ul class="dropdown-menu">
															<li class="dropdown-submenu">
																<a class="dropdown-item" href="#">جزئیات محصول</a>
																<ul class="dropdown-menu">
																	<li><a class="dropdown-item" href="shop-product-full-width.html">تمام عرض</a></li>
																	<li><a class="dropdown-item" href="shop-product-sidebar-right.html">نوار کناری راست</a></li>
																	<li><a class="dropdown-item" href="shop-product-sidebar-left.html">نوار کناری چپ</a></li>
																	<li><a class="dropdown-item" href="shop-product-sidebar-left-and-right.html">نوار کناری چپ و راست</a></li>
																</ul>
															</li>
															<li><a class="dropdown-item" href="shop-4-columns.html">4 ستون</a></li>
															<li class="dropdown-submenu">
																<a class="dropdown-item" href="#">3 ستون</a>
																<ul class="dropdown-menu">
																	<li><a class="dropdown-item" href="shop-3-columns-full-width.html">تمام عرض</a></li>
																	<li><a class="dropdown-item" href="shop-3-columns-sidebar-right.html">نوار کناری راست</a></li>
																	<li><a class="dropdown-item" href="shop-3-columns-sidebar-left.html">نوار کناری چپ </a></li>
																</ul>
															</li>
															<li class="dropdown-submenu">
																<a class="dropdown-item" href="#">2 ستون</a>
																<ul class="dropdown-menu">
																	<li><a class="dropdown-item" href="shop-2-columns-full-width.html">تمام عرض</a></li>
																	<li><a class="dropdown-item" href="shop-2-columns-sidebar-right.html">نوار کناری راست</a></li>
																	<li><a class="dropdown-item" href="shop-2-columns-sidebar-left.html">نوار کناری چپ </a></li>
																	<li><a class="dropdown-item" href="shop-2-columns-sidebar-left-and-right.html">نوار کناری چپ و راست</a></li>
																</ul>
															</li>
															<li class="dropdown-submenu">
																<a class="dropdown-item" href="#">1 ستون</a>
																<ul class="dropdown-menu">
																	<li><a class="dropdown-item" href="shop-1-column-full-width.html">تمام عرض</a></li>
																	<li><a class="dropdown-item" href="shop-1-column-sidebar-right.html">نوار کناری راست</a></li>
																	<li><a class="dropdown-item" href="shop-1-column-sidebar-left.html">نوار کناری چپ </a></li>
																	<li><a class="dropdown-item" href="shop-1-column-sidebar-left-and-right.html">نوار کناری چپ و راست</a></li>
																</ul>
															</li>
															<li><a class="dropdown-item" href="shop-cart.html">سبد خرید</a></li>
															<li><a class="dropdown-item" href="shop-login.html">ورود</a></li>
															<li><a class="dropdown-item" href="shop-checkout.html">پرداخت</a></li>
														</ul>
													</li>
												</ul>
											</nav>
										</div>
									</div>
								</div>
							</div>
							<div class="header-column header-column-border-left flex-grow-0 justify-content-center">
								<div class="header-row pl-4 justify-content-end">
									<ul class="header-social-icons social-icons d-none d-sm-block social-icons-clean m-0">
										<li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
										<li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
										<li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
									</ul>
									<button class="btn header-btn-collapse-nav ml-0 ml-sm-3" data-toggle="collapse" data-target=".header-nav-main nav">
										<i class="fas fa-bars"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</header>

            {% block main %}
            {% endblock %}
			<footer id="footer">
				<div class="container">
					<div class="footer-ribbon">
						<span>در ارتباط باشید</span>
					</div>
					<div class="row py-5 my-4">
						<div class="col-md-6 col-lg-4 mb-4 mb-lg-0 pb-2 pb-lg-0">
							<h5 class="text-3 mb-3">خبرنامه</h5>
							<p class="pr-1">از آخرین ویژگی ها و به‌روزرسانی های ما با خبر شوید. ایمیل خود را وارد کرده و مشترک خبرنامه ما شوید.</p>
							<div class="alert alert-success d-none" id="newsletterSuccess">
								<strong>موفقیت!</strong> شما به لیست ایمیل ما افزوده شدید.
							</div>
							<div class="alert alert-danger d-none" id="newsletterError"></div>
							<form id="newsletterForm" action="php/newsletter-subscribe.php" method="POST" class="mr-md-4 mb-3">
								<div class="input-group input-group-rounded">
									<input class="form-control form-control-sm bg-light text-left" placeholder="آدرس ایمیل" dir="ltr" name="newsletterEmail" id="newsletterEmail" type="text">
									<span class="input-group-append">
										<button class="btn btn-light text-color-dark" type="submit"><strong>برو!</strong></button>
									</span>
								</div>
							</form>
						</div>
						<!-- <div class="col-md-6 col-lg-3 mb-4 mb-lg-0 pb-2 pb-lg-0">
							<h5 class="text-3 mb-3">جدیدترین توییت ها</h5>
							<div id="tweet" class="twitter mb-2" data-plugin-tweets data-plugin-options="{'username': 'rtltheme', 'count': 2}">
								<p class="mb-0">لطفا منتظر باشید ...</p>
							</div>
						</div> -->


						
						<div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
							<h3 class="text-3 mb-3" >مطالب اخیر</h3>
							<ul class="list-unstyled mb-0">
								{% for item in last3%}
								<li class="media mb-3 pb-1">
									<article class="d-flex">
										<a href="#">
											<img class="mr-3 rounded-circle" src="{{item.thumbnail.url}}" alt="The post image" style="max-width: 70px;">
										</a>
										<div class="media-body">
											<a href="{% url 'bloga:detail' item.slug %}">
												<h4 class="text-color-default font-weight-normal line-height-8 text-3 opacity-8 primary-font mb-1 mt-n1">{{item.title}}</h4>
												<p class="text-2 mb-0">{{item.jpublish}}</p>
											</a>
										</div>
									</article>
								</li>
								{% endfor %}
							</ul>
						</div>
						<div class="col-md-6 col-lg-2">
							<h3 class="text-3 mb-3">دسته‌بندی ها</h3>
							<p class="mb-2">
								{%for item in categories%}
								<a href="#"><span class="badge badge-dark bg-color-primary badge-sm py-2 mr-1 mb-2 text-uppercase">{{item.title}}</span></a>
								{% endfor %}
							</p>
						</div>
						<div class="col-md-6 col-lg-2">
							<h5 class="text-3 mb-3 pb-1">ما را دنبال کنید</h5>
							<ul class="social-icons">
								<li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
								<li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
								<li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container py-2">
						<div class="row py-4">
							<div class="col-lg-1 d-flex align-items-center justify-content-center justify-content-lg-start mb-2 mb-lg-0 mt-1 mt-lg-0">
								<a href="index.html" class="logo pr-0 pr-lg-3">
									<img alt="Porto Website Template" src="/static/porto/img/logo-footer.png" class="opacity-5" height="33">
								</a>
							</div>
							<div class="col-lg-7 d-flex align-items-center justify-content-center justify-content-lg-start mb-4 mb-lg-0">
								<p>ارائه شده در وب‌سایت راست‌چین</p>
							</div>
							<div class="col-lg-4 d-flex align-items-center justify-content-center justify-content-lg-end">
								<nav id="sub-menu">
									<ul>
										<li><i class="fas fa-angle-left"></i><a href="page-faq.html" class="ml-1 text-decoration-none"> سوالات متداول</a></li>
										<li><i class="fas fa-angle-left"></i><a href="sitemap.html" class="ml-1 text-decoration-none"> نقشه سایت</a></li>
										<li><i class="fas fa-angle-left"></i><a href="contact-us.html" class="ml-1 text-decoration-none"> تماس با ما</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>


        {% block js%}
        {% endblock %}

	</body>
</html>

templates/projects/project_detail.html
{% extends 'projects/base.html' %}



{% block css %}

<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

<!-- Vendor CSS -->
<link rel="stylesheet" href="/static/porto/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/porto/vendor/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="/static/porto/vendor/animate/animate.min.css">
<link rel="stylesheet" href="/static/porto/vendor/simple-line-icons/css/simple-line-icons.min.css">
<link rel="stylesheet" href="/static/porto/vendor/owl.carousel/assets/owl.carousel.min.css">
<link rel="stylesheet" href="/static/porto/vendor/owl.carousel/assets/owl.theme.default.min.css">
<link rel="stylesheet" href="/static/porto/vendor/magnific-popup/magnific-popup.min.css">

<!-- Theme CSS -->
<link rel="stylesheet" href="/static/porto/css/theme.css">
<link rel="stylesheet" href="/static/porto/css/theme-elements.css">
<link rel="stylesheet" href="/static/porto/css/theme-blog.css">
<link rel="stylesheet" href="/static/porto/css/theme-shop.css">

<!-- Demo CSS -->


<!-- Skin CSS -->
<link rel="stylesheet" href="/static/porto/css/skins/default.css"> 

<!-- Theme Custom CSS -->
<link rel="stylesheet" href="/static/porto/css/custom.css">

<!-- Head Libs -->
<script src="/static/porto/vendor/modernizr/modernizr.min.js"></script>

{% endblock %}

{% block main%}

<div role="main" class="main">
	{% for item in project %}
	<section class="page-header page-header-modern bg-color-light-scale-1 page-header-md ">
		<div class="container-fluid">
			<div class="row align-items-center">

				<div class="col">
				</div>
				<div class="col">
					<div class="row">
						<div class="col-md-12 align-self-center p-static order-2 text-center">
							<div class="overflow-hidden pb-1 mb-n1">
								<h1 class="text-dark font-weight-bold text-9 appear-animation mt-1 mb-n2" data-appear-animation="maskUp" data-appear-animation-delay="100">{{item.project_title}}</h1>
							</div>
						</div>
						<div class="col-md-12 align-self-center order-1">
							<ul class="breadcrumb d-block text-center appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="300">
								<li><a href="/">خانه</a></li>
								<li><a href="/projects">پروژه ها</a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col">
				</div>
			</div>
		</div>
	</section>

	<div class="container py-4">

		<div class="row">
			<div class="col appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300">

				<div class="owl-carousel owl-theme nav-inside nav-inside-edge nav-squared nav-with-transparency nav-dark nav-lg d-block overflow-hidden" data-plugin-options="{'items': 1, 'margin': 10, 'loop': false, 'nav': true, 'dots': false, 'autoHeight': true}" style="height: 510px;">
					<div>
						<div class="img-thumbnail border-0 border-radius-0 p-0 d-block">
							<img src="{{item.project_thumbnail.url}}" class="img-fluid border-radius-0" alt="">
						</div>
					</div>
				</div>

			</div>
		</div>
		<div class="row pt-4 mt-2 mb-5">
			<div class="col-md-7">

				<h2 class="text-color-dark font-weight-normal text-5 mb-3"><strong class="font-weight-extra-bold">توضیحات</strong> پروژه</h2>

				<p>{{item.project_description}}</p>

				<hr class="solid my-5">

				<strong class="text-uppercase text-1 mr-3 text-dark float-left position-relative top-2">اشتراک گذاری</strong>
				<ul class="social-icons">
					<li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
					<li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
					<li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
				</ul>

			</div>
			<div class="col-md-5 mt-5 mt-md-0">
				<h2 class="text-color-dark font-weight-normal text-5 mb-3"><strong class="font-weight-extra-bold">جزئیات</strong> پروژه</h2>
				<ul class="list list-icons list-primary list-borders text-2">
					<li><i class="fas fa-caret-left left-10"></i> <strong class="text-color-primary">مشتری:</strong> {{item.project_customer}}</li>
					<li><i class="fas fa-caret-left left-10"></i> <strong class="text-color-primary">تاریخ:</strong> {{item.jmonth}} {{item.jyear}}</li>
					<li><i class="fas fa-caret-left left-10"></i> <strong class="text-color-primary">مهارت ها:</strong> {% for cat in project_category %}<a href="#" class="badge badge-dark badge-sm badge-pill px-2 py-1 ml-1">{{cat.title}}</a>{% endfor %}</li>
					<li><i class="fas fa-caret-left left-10"></i> <strong class="text-color-primary">آدرس پروژه:</strong> <a href="{{item.project_address}}" target="_blank" class="text-dark">{{item.project_address}}</a></li>
				</ul>
			</div>
		</div>

	</div>
	{% endfor %}
</div>

<section class="section section-height-3 bg-color-grey m-0 border-0">
	<div class="container py-4">
		<h4 class="mb-4 text-4"><strong class="font-weight-extra-bold">پروژه های</strong> اخیر</h4>
		<div class="row">
		{% for item in last4 %}
			<div class="col-12 col-sm-6 col-lg-3 mb-4">
				<div class="portfolio-item">
					<a href="{% url 'project:detail' item.project_slug  %}">
						<span class="thumb-info thumb-info-lighten thumb-info-no-borders border-radius-0">
							<span class="thumb-info-wrapper border-radius-0">
								<img src="{{item.project_thumbnail.url}}" class="img-fluid border-radius-0" alt="">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">{{item.project_title}}</span>
									<span class="thumb-info-type">{{item.project_subject}}</span>
								</span>
								<span class="thumb-info-action">
									<span class="thumb-info-action-icon bg-dark opacity-8"><i class="fas fa-plus"></i></span>
								</span>
							</span>
						</span>
					</a>
				</div>
			</div>
		{% endfor %}
		</div>
	</div>
</section>

{% endblock %}


{% block js%}
<!-- Vendor -->
<script src="/static/porto/vendor/jquery/jquery.min.js"></script>
<script src="/static/porto/vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="/static/porto/vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="/static/porto/vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="/static/porto/vendor/popper/umd/popper.min.js"></script>
<script src="/static/porto/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/porto/vendor/common/common.min.js"></script>
<script src="/static/porto/vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="/static/porto/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="/static/porto/vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="/static/porto/vendor/jquery.lazyload/jquery.lazyload.min.js"></script>
<script src="/static/porto/vendor/isotope/jquery.isotope.min.js"></script>
<script src="/static/porto/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="/static/porto/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="/static/porto/vendor/vide/jquery.vide.min.js"></script>
<script src="/static/porto/vendor/vivus/vivus.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="/static/porto/js/theme.js"></script>

<!-- Theme Custom -->
<script src="/static/porto/js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="/static/porto/js/theme.init.js"></script>

<!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-12345678-1', 'auto');
	ga('send', 'pageview');
</script>
	-->

{% endblock %}