alfax/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
urlpatterns = [
    path('dashboard/karfarmaonline/', include('karfarmaonline.urls')),
    path('', include('land.urls')),
    path('', include("authentication.urls")), 
    path('dashboard/', include('dashboard.urls')),
    path('blog/', include('blog.urls')),
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG :
    urlpatterns += [
        # ... the rest of your URLconf goes here ...
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path

from . import views


app_name = "bloga"

urlpatterns = [
    path('', views.blog_view, name='blog'),
    re_path(r'article/(?P<slug>[-\w]+)/', views.article_detail, name="detail"),
]

dashboard/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contacts'),
    path('soon/', views.sakht, name='soon'),
    re_path(r'^.*\.*', views.pages, name='pages'),
]

karfarmaonline/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.utils import timezone
from extensions.utils import jalali_converter
from datetime import datetime, timedelta

class expenceManager(models.Manager):
    def total(self, project):
        total = expence.objects.filter(project=project).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total

    def total_project(self, project):
        total = expence.objects.filter(project=project)
        return total
    def total_project_user(self, user,project):
        total = expence.objects.filter(user=user,project=project)
        return total
        
    def total_per_user(self, user):
        total = expence.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total
    def total_per_user_project(self, user, project):
        total = expence.objects.filter(user=user, project=project).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total
    def total_last_7_days(self, user):
        total = expence.objects.filter(user=user, pub_date= datetime.now()-timedelta(days=7)).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total
    def Category_expence(self, project):
        a = expence.objects.filter(project=project, category_pay='a').aggregate(Sum('amount'))['amount__sum']
        b = expence.objects.filter(project=project, category_pay='b').aggregate(Sum('amount'))['amount__sum']
        c = expence.objects.filter(project=project, category_pay='c').aggregate(Sum('amount'))['amount__sum']
        d = expence.objects.filter(project=project, category_pay='d').aggregate(Sum('amount'))['amount__sum']
        e = expence.objects.filter(project=project, category_pay='e').aggregate(Sum('amount'))['amount__sum']
        f = expence.objects.filter(project=project, category_pay='f').aggregate(Sum('amount'))['amount__sum']
        g = expence.objects.filter(project=project, category_pay='g').aggregate(Sum('amount'))['amount__sum']
        i = expence.objects.filter(project=project, category_pay='i').aggregate(Sum('amount'))['amount__sum']
        j = expence.objects.filter(project=project, category_pay='j').aggregate(Sum('amount'))['amount__sum']
        k = expence.objects.filter(project=project, category_pay='k').aggregate(Sum('amount'))['amount__sum']
        l = expence.objects.filter(project=project, category_pay='l').aggregate(Sum('amount'))['amount__sum']
        m = expence.objects.filter(project=project, category_pay='m').aggregate(Sum('amount'))['amount__sum']
        if a is None : a= 0
        if b is None : b= 0
        if c is None : c= 0
        if d is None : d= 0
        if e is None : e= 0
        if f is None : f= 0
        if g is None : g= 0
        if k is None : k= 0
        if i is None : i= 0
        if j is None : j= 0
        if l is None : l= 0
        if m is None : m= 0


        return j , a+b ,g+i,f, c+d, e, k, m+l

        
class incomeManager(models.Manager):
    def total(self, project):
        total = income.objects.filter(project=project).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total
    def total_per_user(self, user):
        total = income.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total
    def total_per_user_project(self, user, project):
        total = income.objects.filter(user=user, project=project).aggregate(Sum('amount'))['amount__sum']
        if total is None : total = 0
        return total

class Managera(models.Manager):

    def is_member_of(self, user):
        is_member = ProjectModel.objects.filter(Members=user)
        if is_member.count() != 0:
            return True
        else:
            return False

    def is_member_of_project(self, user , id):
        is_member = ProjectModel.objects.filter(Members=user ,id = id)
        if is_member.count() != 0:
            return True
        else:
            return False

    def is_manager(self, user):
        is_manager =ProjectModel.objects.filter(Manager=user)
        if is_manager.count() != 0:
            return True
        else:
            return False
            
    def is_manager_project(self, user, id):
        is_managera =ProjectModel.objects.filter(Manager=user, id = id)
        if is_managera.count() != 0:
            return True
        else:
            return False

    def is_user(self, number):
        is_user = User.objects.filter(username=number)
        print(is_user)

        if is_user.count() != 0 :
            return True
        else :
            return False
    def project_count(self, user):
        proj_count = ProjectModel.objects.filter(Manager=user).count()+ProjectModel.objects.filter(Members=user).count()
        return proj_count
    




class ProjectModel(models.Model):
    METHOD_CHOICE = (
        ('a','در حال انجام'),
        ('b','پایان یافته'),
    )

    name= models.CharField(max_length=100,verbose_name="نام پروژه") 
    zirbana = models.IntegerField(verbose_name="مساحت زیر بنا متر مربع")
    tedad_tabaqat = models.IntegerField(verbose_name="تعداد طبقات پروژه")
    address = models.CharField(max_length=150 ,blank=True, null=True , verbose_name="آددرس پروژه")
    Members = models.ManyToManyField(User, related_name='member',verbose_name="انتخاب شرکا", blank=True)
    Manager = models.ForeignKey(User,related_name='manager' ,on_delete=models.CASCADE, verbose_name="مدیر پروژه")
    description = models.TextField(max_length=400 , verbose_name="توضیحات پروژه",blank=True)
    project_status = models.CharField(max_length=1,choices=METHOD_CHOICE, verbose_name="وضعیت پروژه" )
    created_date = models.DateField(auto_now_add=True, verbose_name= "تاریخ ایجاد پروژه")
    
    objects = Managera()

    class Meta :
        verbose_name = "پروژه عمرانی"
        verbose_name_plural= "پروژه های عمرانی"
        
    def __str__(self):
        return self.name
    def __unicode__(self):
        return self.name
    def jpub_date(self):
        return jalali_converter(self.created_date)

class income(models.Model):
    METHOD_CHOICES = (
        ('n', 'نقد'),
        ('c','چک'),
    )
    CATEGORY_CHOICES = (
        ('a','تامین مالی از مالک'),
        ('b','فروش آهن آلات'),
        ('c','فروش ملک'),
        ('d','سایر'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, verbose_name="هزینه شده توسط ")
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE, verbose_name="پروژه مربوطه")
    title = models.CharField(max_length=200,verbose_name="عنوان هزینه کرد")
    amount = models.BigIntegerField(verbose_name="مقدار هزینه")
    description = models.TextField(max_length=200, blank=True, null=True,verbose_name="توضیحات")
    pay_mehod = models.CharField(max_length=1, choices=METHOD_CHOICES,verbose_name="شیوه پرداخت")
    category_pay = models.CharField(max_length=1, choices=CATEGORY_CHOICES, verbose_name="از کدام منبع درآمد داشتید")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار")

    objects = incomeManager()

    class Meta :
        verbose_name = "درآمد"
        verbose_name_plural= "درآمد ها"
        
    def __str__(self):
        return "{} - {}".format(self.title,self.amount)
    def __unicode__(self):
        return "{} - {}".format(self.title,self.amount)

    def jpub_date(self):
        return jalali_converter(self.pub_date)


class expence(models.Model):
    METHOD_CHOICES = (
        ('n', 'نقد'),
        ('c','چک'),
    )
    CATEGORY_CHOICE = (
        ('a','صدور پروانه'),
        ('b','شهرداری'),
        ('c','آرماتور بند'),
        ('d','شرکت بتن'),
        ('e','آهن آلات'),
        ('f','تاسیسات'),
        ('g','مصالح'),
        ('i','دستمزد کارگر بنا'),
        ('j','تخریب'),
        ('k','آب و برق و گاز'),
        ('l','کرایه تجهیزات'),
        ('m','متفرقه'),

    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, verbose_name="هزینه شده توسط ")
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE, verbose_name="پروژه مربوطه")
    title = models.CharField(max_length=200,verbose_name="عنوان")
    amount = models.BigIntegerField(verbose_name="مقدار هزینه کرد به تومان")
    description = models.TextField(max_length=200, blank=True, null=True,verbose_name="توضیحات")
    pay_mehod = models.CharField(max_length=1, choices=METHOD_CHOICES,verbose_name="شیوه پرداخت")
    category_pay = models.CharField(max_length=1, choices=CATEGORY_CHOICE, verbose_name="در کدام شاخه هزینه کردید")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار")

    objects = expenceManager()

    class Meta :
        verbose_name = "هزینه کرد"
        verbose_name_plural= " هزینه کرد ها"
    

    def __str__(self):
        return "{} - {}".format(self.title,self.amount)


    def __unicode__(self):
        return "{} - {}".format(self.title,self.amount)

    def jpub_date(self):
        return jalali_converter(self.pub_date)

dashboard/forms.py
# -*- encoding: utf-8 -*-

from .models import Contacts
from django import forms
from django.forms import TextInput, EmailInput,Textarea, Select,NumberInput
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contacts
        fields = ('nameandfamily','companyname','mobile','phone','address','email')
        widgets = {
            'nameandfamily':TextInput(attrs={'class':'form-control','placeholder':'نام و نام خانوادگی'}),
            'companyname':TextInput(attrs={'class':'form-control','placeholder':'نام شرکت'}),
            'mobile':NumberInput(attrs={'class':'form-control','placeholder':'شماره همراه'}),
            'phone':NumberInput(attrs={'class':'form-control','placeholder':'تلفن ثابت'}),
            'address':TextInput(attrs={'class':'form-control','placeholder':'آدرس'}),
            'email':EmailInput(attrs={'class':'form-control','placeholder':'ایمیل'}),
        }
    

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django import template
from .models import *
from django.contrib.auth.models import User
from .forms import ContactForm
from django.contrib import messages


@login_required(login_url="/login/")
def contact(request):
    ## TODO big Probelm with GET Method
    form = ContactForm()
    if request.GET.get('remove', False)  == 'true' :
        if request.GET.get('all', False) == 'true':
            Contacts.objects.all().delete()
        contact_id = request.GET.get('contact_id', False)
        Contacts.objects.filter(id=contact_id).delete()
    
    if request.method == "POST" :
        form = ContactForm(request.POST or None)
        if form.is_valid():
            nameandfamily= form.cleaned_data.get("nameandfamily")
            companyname= form.cleaned_data.get("companyname")
            mobile= form.cleaned_data.get("mobile")
            phone= form.cleaned_data.get("phone")
            address= form.cleaned_data.get("address")
            email= form.cleaned_data.get("email")
            user = request.user
            oj = Contacts(nameandfamily=nameandfamily,companyname=companyname,mobile=mobile,phone=phone,address=address,email=email,user=user)
            oj.save()
            messages.info(request, 'مخاطب با موفقیت ذخیره شد')

    profile  = UserProfile.objects.filter(user=request.user)
    context = {"contacts": Contacts.objects.filter(user=request.user),"user":request.user,"profiles":profile, 'form':form}
    return render(request, "dashboard/table-datatable.html", context)

@login_required(login_url="/login/")
def index(request):
    profile  = UserProfile.objects.all().filter(user=request.user)
    context = {"user":request.user,"profiles":profile}
    context['segment'] = 'index'

    html_template = loader.get_template( 'dashboard/main.html' )
    return HttpResponse(html_template.render(context, request))

@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:
        
        load_template      = request.path.split('/')[-1]
        context['segment'] = load_template
        
        html_template = loader.get_template( load_template )
        return HttpResponse(html_template.render(context, request))
        
    except template.TemplateDoesNotExist:

        html_template = loader.get_template( 'dashboard/error-404.html' )
        return HttpResponse(html_template.render(context, request))

    except:
    
        html_template = loader.get_template( 'dashboard/error-500.html' )
        return HttpResponse(html_template.render(context, request))

@login_required(login_url="/login/")
def sakht(request):
    context = {"user":request.user}
    context['segment'] = 'index'
    html_template = loader.get_template( 'dashboard/page-maintenance.html' )
    return HttpResponse(html_template.render(context, request))

templates/dashboard/karon_expence.html
{% extends 'dashboard/base.html' %}

{% block css %}
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/vendors-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/charts/apexcharts.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/extensions/tether-theme-arrows.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/extensions/tether.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/extensions/shepherd-theme-default.css">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/bootstrap-extended.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/colors.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/components.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/themes/dark-layout.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/themes/semi-dark-layout.min.css">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/core/menu/menu-types/vertical-menu.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/core/colors/palette-gradient.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/pages/dashboard-analytics.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/pages/card-analytics.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/plugins/tour/tour.min.css">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/custom-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/assets/css/style-rtl.css">
    <!-- END: Custom CSS-->
{% endblock %}

{% block main%}

    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="header-navbar-shadow"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body"><!-- Dashboard Analytics Start -->
            <section id="floating-label-layouts">
                <div class="row match-height">
                    <div class="col-md-6 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title"> ثبت یک هزینه کرد در سیستم</h4>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    {% for message in messages %}
                                    <div class="alert alert-success" role="alert">
                                      <p>{{message}}</p>
                                    </div>
                                    {% endfor %}
                                    <form class="form" method="POST">
                                        {% csrf_token %}
                                        <div class="form-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="form-label-group">
                                                        {{form.title}}
                                                        <!-- <input type="text" id="last-name-column" class="form-control" placeholder="زیر بنای پروژه" name="zirbana"> -->
                                                        <label for="last-name-column">عنوان هزینه کرد</label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-label-group">
                                                             
                                                        {{form.amount}}
                                                        <!-- <input type="text" id="city-column" class="form-control" placeholder="تعداد طبقات" name="city-column"> -->
                                                        <label for="city-column"> مقدار هزینه کرد به تومان</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-12">
                                                    <div class="form-label-group">
                                                        انتخاب پروژه
                                                        {{form.project}}
                                                        <!-- <input type="text" id="first-name-column" class="form-control" placeholder="نام پروژه" name="project_name"> -->
                                                        <label for="id_project">انتخاب پروژه </label>
                                                    </div>
                                                </div>

                                                <div class="col-md-6 col-12">
                                                    <div class="form-label-group">
                                                        انتخاب روش واریز
                                                        {{form.pay_mehod}}
                                                        <!-- <input type="text" id="country-floating" class="form-control" name="country-floating" placeholder="آدرس پروژه"> -->
                                                        <label for="id_pay_mehod">روش واریز </label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-label-group">
                                                        انتخاب دسته بندی
                                                        {{form.category_pay}}
                                                        <!-- <input type="email" id="email-id-column" class="form-control" name="email-id-column" placeholder="وضعیت پروژه"> -->
                                                        <label for="id_category_pay">دسته بندی </label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-label-group">
                                                        {{form.description}}
                                                        <!-- <input type="email" id="email-id-column" class="form-control" name="email-id-column" placeholder="وضعیت پروژه"> -->
                                                        <label for="email-id-column">توضیحات </label>
                                                    </div>
                                                </div>

                              <div class="col-12">
                                                    <button type="submit" class="btn btn-primary mr-1 mb-1">ثبت کن</button>
                                                    <button type="reset" class="btn btn-outline-warning mr-1 mb-1">تنظیم مجدد</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-12">
                        <div class="card">
                            <div class="card-content">
                              <div class="card-body">
                                <img class="card-img img-fluid mb-1" src="/static/vuexy/app-assets/images/pages/content-img-2.jpg"
                                  alt="Card image cap">
                                <h5 class="mt-1">{{user.first_name}}</h5>
                                <p class="card-text"> هزینه کرد از همه پروژه ها</p>
                                <hr class="my-1">
                                <div class="d-flex justify-content-between mt-2">
                                  <div class="float-left">
                                    <p class="font-medium-2 mb-0">۰ ريال</p>
                                    <p class="">هزینه کرد</p>
                                  </div>
                                  <div class="float-right">
                                    <p class="font-medium-2 mb-0">تاریخ</p>
                                    <p class="">تاریخ </p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>  
                </div>
            </section>
<!-- Dashboard Analytics end -->

        </div>
      </div>
    </div>

{% endblock %}


{% block js%}
    <!-- BEGIN: Vendor JS-->
    <script src="/static/vuexy/app-assets/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="/static/vuexy/app-assets/vendors/js/charts/apexcharts.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/extensions/tether.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/extensions/shepherd.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/pdfmake.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/vfs_fonts.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/buttons.html5.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/buttons.print.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js"></script>
    <script src="/static/vuexy/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="/static/vuexy/app-assets/js/core/app-menu.min.js"></script>
    <script src="/static/vuexy/app-assets/js/core/app.min.js"></script>
    <script src="/static/vuexy/app-assets/js/scripts/components.min.js"></script>
    <script src="/static/vuexy/app-assets/js/scripts/customizer.min.js"></script>
    <script src="/static/vuexy/app-assets/js/scripts/footer.min.js"></script>
    <!-- END: Theme JS-->
    <script src="/static/vuexy/app-assets/js/scripts/cards/card-analytics.min.js"></script>
    <!-- BEGIN: Page JS-->
    <script src="/static/vuexy/app-assets/js/scripts/pages/dashboard-analytics.min.js"></script>
    <script src="/static/vuexy/app-assets/js/scripts/datatables/datatable.min.js"></script>
    <!-- END: Page JS-->
{% endblock %}

templates/dashboard/page-maintenance.html
<!DOCTYPE html>
<!--
Template Name: Vuexy - Vuejs, HTML & Laravel Admin Dashboard Template
Author: PixInvent
Website: http://www.pixinvent.com/
Contact: hello@pixinvent.com
Follow: www.twitter.com/pixinvents
Like: www.facebook.com/pixinvents
Purchase: https://www.rtl-theme.com/vuexy-Admin-Dashboard-Template
Renew Support: https://www.rtl-theme.com/vuexy-Admin-Dashboard-Template
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.

-->
<html class="loading" lang="en" data-textdirection="rtl">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>تعمیر - Vuexy - قالب مدیریتی نوین پردازش آروکو</title>
    <link rel="apple-touch-icon" href="/static/vuexy/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="/static/vuexy/app-assets/images/ico/favicon.ico">
    <link href="/static/vuexy/app-assets/images/fonts.googleapis.css" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/vendors/css/vendors-rtl.min.css">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/bootstrap-extended.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/colors.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/components.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/themes/dark-layout.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/themes/semi-dark-layout.min.css">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/core/menu/menu-types/vertical-menu.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/core/colors/palette-gradient.min.css">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="/static/vuexy/app-assets/css-rtl/custom-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/static/vuexy/assets/css/style-rtl.css">
    <!-- END: Custom CSS-->

  </head>
  <!-- END: Head-->

  <!-- BEGIN: Body-->
  <body class="vertical-layout vertical-menu-modern semi-dark-layout 1-column  navbar-floating footer-static bg-full-screen-image  blank-page blank-page" data-open="click" data-menu="vertical-menu-modern" data-col="1-column" data-layout="semi-dark-layout">
    <!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="header-navbar-shadow"></div>
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body"><!-- maintenance -->
<section class="row flexbox-container">
  <div class="col-xl-7 col-md-8 col-12 d-flex justify-content-center">
    <div class="card auth-card bg-transparent shadow-none rounded-0 mb-0 w-100">
      <div class="card-content">
        <div class="card-body text-center">
          <img src="/static/vuexy/app-assets/images/pages/maintenance-2.png" class="img-fluid align-self-center" alt="branding logo">
          <h1 class="font-large-2 my-1">در حال تعمیر هستیم !</h1>
          <p class="px-2">این صفحات در حال توسعه می باشند لطفا بعدا مراجعه کنید</p>
          <a class="btn btn-primary btn-lg mt-1" href="/dashboard/karfarmaonline/">بازگشت به خانه</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- maintenance end -->

        </div>
      </div>
    </div>
    <!-- END: Content-->


    <!-- BEGIN: Vendor JS-->
    <script src="/static/vuexy/app-assets/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="/static/vuexy/app-assets/js/core/app-menu.min.js"></script>
    <script src="/static/vuexy/app-assets/js/core/app.min.js"></script>
    <script src="/static/vuexy/app-assets/js/scripts/components.min.js"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <!-- END: Page JS-->

  </body>
  <!-- END: Body-->
</html>